//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ING.EFatura
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class ProcessingFault
    {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class SendUBLResponseType
    {
        
        private string envUUIDField;
        
        private string uUIDField;
        
        private string idField;
        
        private string custInvIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EnvUUID
        {
            get
            {
                return this.envUUIDField;
            }
            set
            {
                this.envUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustInvID
        {
            get
            {
                return this.custInvIDField;
            }
            set
            {
                this.custInvIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http:/fitcons.com/eInvoice/", ConfigurationName="ING.EFatura.ClientEInvoiceServicesPort")]
    public interface ClientEInvoiceServicesPort
    {
        
        // CODEGEN: Generating message contract since the operation sendUBL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sendUBL", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ING.EFatura.ProcessingFault), Action="sendUBL", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ING.EFatura.sendUBLResponse sendUBL(ING.EFatura.sendUBLRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sendUBL", ReplyAction="*")]
        System.Threading.Tasks.Task<ING.EFatura.sendUBLResponse> sendUBLAsync(ING.EFatura.sendUBLRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUBLList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getUBLList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ING.EFatura.ProcessingFault), Action="getUBLList", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ING.EFatura.getUBLListResponse getUBLList(ING.EFatura.getUBLListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getUBLList", ReplyAction="*")]
        System.Threading.Tasks.Task<ING.EFatura.getUBLListResponse> getUBLListAsync(ING.EFatura.getUBLListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUBL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getUBL", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ING.EFatura.ProcessingFault), Action="getUBL", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ING.EFatura.getUBLResponse getUBL(ING.EFatura.getUBLRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getUBL", ReplyAction="*")]
        System.Threading.Tasks.Task<ING.EFatura.getUBLResponse> getUBLAsync(ING.EFatura.getUBLRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getEnvelopeStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getEnvelopeStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ING.EFatura.ProcessingFault), Action="getEnvelopeStatus", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ING.EFatura.getEnvelopeStatusResponse getEnvelopeStatus(ING.EFatura.getEnvelopeStatusRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getEnvelopeStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ING.EFatura.getEnvelopeStatusResponse> getEnvelopeStatusAsync(ING.EFatura.getEnvelopeStatusRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getInvoiceView is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getInvoiceView", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ING.EFatura.ProcessingFault), Action="getInvoiceView", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ING.EFatura.getInvoiceViewResponse1 getInvoiceView(ING.EFatura.getInvoiceViewRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getInvoiceView", ReplyAction="*")]
        System.Threading.Tasks.Task<ING.EFatura.getInvoiceViewResponse1> getInvoiceViewAsync(ING.EFatura.getInvoiceViewRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getRAWUserList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getRAWUserList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ING.EFatura.ProcessingFault), Action="getRAWUserList", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ING.EFatura.getRAWUserListResponse1 getRAWUserList(ING.EFatura.getRAWUserListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getRAWUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<ING.EFatura.getRAWUserListResponse1> getRAWUserListAsync(ING.EFatura.getRAWUserListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getInvResponses is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getInvResponses", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ING.EFatura.ProcessingFault), Action="getInvResponses", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ING.EFatura.getInvResponsesResponse1 getInvResponses(ING.EFatura.getInvResponsesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getInvResponses", ReplyAction="*")]
        System.Threading.Tasks.Task<ING.EFatura.getInvResponsesResponse1> getInvResponsesAsync(ING.EFatura.getInvResponsesRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class sendUBLRequest
    {
        
        private string vKN_TCKNField;
        
        private string senderIdentifierField;
        
        private string receiverIdentifierField;
        
        private string docTypeField;
        
        private string[] parametersField;
        
        private byte[] docDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VKN_TCKN
        {
            get
            {
                return this.vKN_TCKNField;
            }
            set
            {
                this.vKN_TCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SenderIdentifier
        {
            get
            {
                return this.senderIdentifierField;
            }
            set
            {
                this.senderIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReceiverIdentifier
        {
            get
            {
                return this.receiverIdentifierField;
            }
            set
            {
                this.receiverIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=4)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] DocData
        {
            get
            {
                return this.docDataField;
            }
            set
            {
                this.docDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendUBLRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.sendUBLRequest sendUBLRequest;
        
        public sendUBLRequest1()
        {
        }
        
        public sendUBLRequest1(ING.EFatura.sendUBLRequest sendUBLRequest)
        {
            this.sendUBLRequest = sendUBLRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendUBLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendUBLResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", IsNullable=false)]
        public ING.EFatura.SendUBLResponseType[] sendUBLResponse1;
        
        public sendUBLResponse()
        {
        }
        
        public sendUBLResponse(ING.EFatura.SendUBLResponseType[] sendUBLResponse1)
        {
            this.sendUBLResponse1 = sendUBLResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getUBLListRequest
    {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string[] uUIDField;
        
        private string docTypeField;
        
        private string typeField;
        
        private string[] parametersField;
        
        private System.DateTime fromDateField;
        
        private bool fromDateFieldSpecified;
        
        private System.DateTime toDateField;
        
        private bool toDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN
        {
            get
            {
                return this.vKN_TCKNField;
            }
            set
            {
                this.vKN_TCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUID", Order=2)]
        public string[] UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=5)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime FromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromDateSpecified
        {
            get
            {
                return this.fromDateFieldSpecified;
            }
            set
            {
                this.fromDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime ToDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToDateSpecified
        {
            get
            {
                return this.toDateFieldSpecified;
            }
            set
            {
                this.toDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class GetUBLListResponseType
    {
        
        private string uUIDField;
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string envTypeField;
        
        private object envUUIDField;
        
        private string idField;
        
        private string custInvIDField;
        
        private System.DateTime insertDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VKN_TCKN
        {
            get
            {
                return this.vKN_TCKNField;
            }
            set
            {
                this.vKN_TCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EnvType
        {
            get
            {
                return this.envTypeField;
            }
            set
            {
                this.envTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object EnvUUID
        {
            get
            {
                return this.envUUIDField;
            }
            set
            {
                this.envUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustInvID
        {
            get
            {
                return this.custInvIDField;
            }
            set
            {
                this.custInvIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime InsertDateTime
        {
            get
            {
                return this.insertDateTimeField;
            }
            set
            {
                this.insertDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUBLListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getUBLListRequest getUBLListRequest;
        
        public getUBLListRequest1()
        {
        }
        
        public getUBLListRequest1(ING.EFatura.getUBLListRequest getUBLListRequest)
        {
            this.getUBLListRequest = getUBLListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUBLListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUBLListResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UBLList", IsNullable=false)]
        public ING.EFatura.GetUBLListResponseType[] getUBLListResponse1;
        
        public getUBLListResponse()
        {
        }
        
        public getUBLListResponse(ING.EFatura.GetUBLListResponseType[] getUBLListResponse1)
        {
            this.getUBLListResponse1 = getUBLListResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getUBLRequest
    {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string[] uUIDField;
        
        private string docTypeField;
        
        private string typeField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN
        {
            get
            {
                return this.vKN_TCKNField;
            }
            set
            {
                this.vKN_TCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUID", Order=2)]
        public string[] UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=5)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUBLRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getUBLRequest getUBLRequest;
        
        public getUBLRequest1()
        {
        }
        
        public getUBLRequest1(ING.EFatura.getUBLRequest getUBLRequest)
        {
            this.getUBLRequest = getUBLRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUBLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUBLResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DocData", DataType="base64Binary", IsNullable=false)]
        public byte[][] getUBLResponse1;
        
        public getUBLResponse()
        {
        }
        
        public getUBLResponse(byte[][] getUBLResponse1)
        {
            this.getUBLResponse1 = getUBLResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getEnvelopeStatusRequest
    {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string[] uUIDField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN
        {
            get
            {
                return this.vKN_TCKNField;
            }
            set
            {
                this.vKN_TCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUID", Order=2)]
        public string[] UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=3)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getEnvelopeStatusResponseType
    {
        
        private string uUIDField;
        
        private System.DateTime issueDateField;
        
        private string documentTypeCodeField;
        
        private string documentTypeField;
        
        private string responseCodeField;
        
        private string descriptionField;
        
        private byte[] docDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocumentTypeCode
        {
            get
            {
                return this.documentTypeCodeField;
            }
            set
            {
                this.documentTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] DocData
        {
            get
            {
                return this.docDataField;
            }
            set
            {
                this.docDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEnvelopeStatusRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getEnvelopeStatusRequest getEnvelopeStatusRequest;
        
        public getEnvelopeStatusRequest1()
        {
        }
        
        public getEnvelopeStatusRequest1(ING.EFatura.getEnvelopeStatusRequest getEnvelopeStatusRequest)
        {
            this.getEnvelopeStatusRequest = getEnvelopeStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEnvelopeStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEnvelopeStatusResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", IsNullable=false)]
        public ING.EFatura.getEnvelopeStatusResponseType[] getEnvelopeStatusResponse1;
        
        public getEnvelopeStatusResponse()
        {
        }
        
        public getEnvelopeStatusResponse(ING.EFatura.getEnvelopeStatusResponseType[] getEnvelopeStatusResponse1)
        {
            this.getEnvelopeStatusResponse1 = getEnvelopeStatusResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getInvoiceViewRequest
    {
        
        private string uUIDField;
        
        private string custInvIDField;
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string typeField;
        
        private string docTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustInvID
        {
            get
            {
                return this.custInvIDField;
            }
            set
            {
                this.custInvIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VKN_TCKN
        {
            get
            {
                return this.vKN_TCKNField;
            }
            set
            {
                this.vKN_TCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getInvoiceViewResponse
    {
        
        private byte[] docDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] DocData
        {
            get
            {
                return this.docDataField;
            }
            set
            {
                this.docDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInvoiceViewRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getInvoiceViewRequest getInvoiceViewRequest;
        
        public getInvoiceViewRequest1()
        {
        }
        
        public getInvoiceViewRequest1(ING.EFatura.getInvoiceViewRequest getInvoiceViewRequest)
        {
            this.getInvoiceViewRequest = getInvoiceViewRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInvoiceViewResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getInvoiceViewResponse getInvoiceViewResponse;
        
        public getInvoiceViewResponse1()
        {
        }
        
        public getInvoiceViewResponse1(ING.EFatura.getInvoiceViewResponse getInvoiceViewResponse)
        {
            this.getInvoiceViewResponse = getInvoiceViewResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getRAWUserListRequest
    {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string roleField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN
        {
            get
            {
                return this.vKN_TCKNField;
            }
            set
            {
                this.vKN_TCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=3)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getRAWUserListResponse
    {
        
        private byte[] docDataField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] DocData
        {
            get
            {
                return this.docDataField;
            }
            set
            {
                this.docDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=1)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRAWUserListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getRAWUserListRequest getRAWUserListRequest;
        
        public getRAWUserListRequest1()
        {
        }
        
        public getRAWUserListRequest1(ING.EFatura.getRAWUserListRequest getRAWUserListRequest)
        {
            this.getRAWUserListRequest = getRAWUserListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRAWUserListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getRAWUserListResponse getRAWUserListResponse;
        
        public getRAWUserListResponse1()
        {
        }
        
        public getRAWUserListResponse1(ING.EFatura.getRAWUserListResponse getRAWUserListResponse)
        {
            this.getRAWUserListResponse = getRAWUserListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getInvResponsesRequest
    {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string[] uUIDField;
        
        private string typeField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN
        {
            get
            {
                return this.vKN_TCKNField;
            }
            set
            {
                this.vKN_TCKNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUID", Order=2)]
        public string[] UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=4)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getInvResponsesResponse
    {
        
        private GetInvResponsesResponseType[] responseField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Response", Order=0)]
        public GetInvResponsesResponseType[] Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=1)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class GetInvResponsesResponseType
    {
        
        private string invoiceUUIDField;
        
        private GetInvResponsesResponseInvResponsesType[] invResponsesField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InvoiceUUID
        {
            get
            {
                return this.invoiceUUIDField;
            }
            set
            {
                this.invoiceUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InvResponses", Order=1)]
        public GetInvResponsesResponseInvResponsesType[] InvResponses
        {
            get
            {
                return this.invResponsesField;
            }
            set
            {
                this.invResponsesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=2)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class GetInvResponsesResponseInvResponsesType
    {
        
        private string envUUIDField;
        
        private string uUIDField;
        
        private string idField;
        
        private System.DateTime insertDateTimeField;
        
        private System.DateTime issueDateField;
        
        private string aRTypeField;
        
        private string[] aRNotesField;
        
        private byte[] docDataField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EnvUUID
        {
            get
            {
                return this.envUUIDField;
            }
            set
            {
                this.envUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime InsertDateTime
        {
            get
            {
                return this.insertDateTimeField;
            }
            set
            {
                this.insertDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime IssueDate
        {
            get
            {
                return this.issueDateField;
            }
            set
            {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ARType
        {
            get
            {
                return this.aRTypeField;
            }
            set
            {
                this.aRTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ARNotes", Order=6)]
        public string[] ARNotes
        {
            get
            {
                return this.aRNotesField;
            }
            set
            {
                this.aRNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=7)]
        public byte[] DocData
        {
            get
            {
                return this.docDataField;
            }
            set
            {
                this.docDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=8)]
        public string[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInvResponsesRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getInvResponsesRequest getInvResponsesRequest;
        
        public getInvResponsesRequest1()
        {
        }
        
        public getInvResponsesRequest1(ING.EFatura.getInvResponsesRequest getInvResponsesRequest)
        {
            this.getInvResponsesRequest = getInvResponsesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInvResponsesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public ING.EFatura.getInvResponsesResponse getInvResponsesResponse;
        
        public getInvResponsesResponse1()
        {
        }
        
        public getInvResponsesResponse1(ING.EFatura.getInvResponsesResponse getInvResponsesResponse)
        {
            this.getInvResponsesResponse = getInvResponsesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ClientEInvoiceServicesPortChannel : ING.EFatura.ClientEInvoiceServicesPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ClientEInvoiceServicesPortClient : System.ServiceModel.ClientBase<ING.EFatura.ClientEInvoiceServicesPort>, ING.EFatura.ClientEInvoiceServicesPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClientEInvoiceServicesPortClient() : 
                base(ClientEInvoiceServicesPortClient.GetDefaultBinding(), ClientEInvoiceServicesPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ClientEInvoiceServicesPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientEInvoiceServicesPortClient(EndpointConfiguration endpointConfiguration) : 
                base(ClientEInvoiceServicesPortClient.GetBindingForEndpoint(endpointConfiguration), ClientEInvoiceServicesPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientEInvoiceServicesPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClientEInvoiceServicesPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientEInvoiceServicesPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClientEInvoiceServicesPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientEInvoiceServicesPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ING.EFatura.sendUBLResponse ING.EFatura.ClientEInvoiceServicesPort.sendUBL(ING.EFatura.sendUBLRequest1 request)
        {
            return base.Channel.sendUBL(request);
        }
        
        public ING.EFatura.SendUBLResponseType[] sendUBL(ING.EFatura.sendUBLRequest sendUBLRequest)
        {
            ING.EFatura.sendUBLRequest1 inValue = new ING.EFatura.sendUBLRequest1();
            inValue.sendUBLRequest = sendUBLRequest;
            ING.EFatura.sendUBLResponse retVal = ((ING.EFatura.ClientEInvoiceServicesPort)(this)).sendUBL(inValue);
            return retVal.sendUBLResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ING.EFatura.sendUBLResponse> ING.EFatura.ClientEInvoiceServicesPort.sendUBLAsync(ING.EFatura.sendUBLRequest1 request)
        {
            return base.Channel.sendUBLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ING.EFatura.sendUBLResponse> sendUBLAsync(ING.EFatura.sendUBLRequest sendUBLRequest)
        {
            ING.EFatura.sendUBLRequest1 inValue = new ING.EFatura.sendUBLRequest1();
            inValue.sendUBLRequest = sendUBLRequest;
            return ((ING.EFatura.ClientEInvoiceServicesPort)(this)).sendUBLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ING.EFatura.getUBLListResponse ING.EFatura.ClientEInvoiceServicesPort.getUBLList(ING.EFatura.getUBLListRequest1 request)
        {
            return base.Channel.getUBLList(request);
        }
        
        public ING.EFatura.GetUBLListResponseType[] getUBLList(ING.EFatura.getUBLListRequest getUBLListRequest)
        {
            ING.EFatura.getUBLListRequest1 inValue = new ING.EFatura.getUBLListRequest1();
            inValue.getUBLListRequest = getUBLListRequest;
            ING.EFatura.getUBLListResponse retVal = ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getUBLList(inValue);
            return retVal.getUBLListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ING.EFatura.getUBLListResponse> ING.EFatura.ClientEInvoiceServicesPort.getUBLListAsync(ING.EFatura.getUBLListRequest1 request)
        {
            return base.Channel.getUBLListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ING.EFatura.getUBLListResponse> getUBLListAsync(ING.EFatura.getUBLListRequest getUBLListRequest)
        {
            ING.EFatura.getUBLListRequest1 inValue = new ING.EFatura.getUBLListRequest1();
            inValue.getUBLListRequest = getUBLListRequest;
            return ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getUBLListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ING.EFatura.getUBLResponse ING.EFatura.ClientEInvoiceServicesPort.getUBL(ING.EFatura.getUBLRequest1 request)
        {
            return base.Channel.getUBL(request);
        }
        
        public byte[][] getUBL(ING.EFatura.getUBLRequest getUBLRequest)
        {
            ING.EFatura.getUBLRequest1 inValue = new ING.EFatura.getUBLRequest1();
            inValue.getUBLRequest = getUBLRequest;
            ING.EFatura.getUBLResponse retVal = ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getUBL(inValue);
            return retVal.getUBLResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ING.EFatura.getUBLResponse> ING.EFatura.ClientEInvoiceServicesPort.getUBLAsync(ING.EFatura.getUBLRequest1 request)
        {
            return base.Channel.getUBLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ING.EFatura.getUBLResponse> getUBLAsync(ING.EFatura.getUBLRequest getUBLRequest)
        {
            ING.EFatura.getUBLRequest1 inValue = new ING.EFatura.getUBLRequest1();
            inValue.getUBLRequest = getUBLRequest;
            return ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getUBLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ING.EFatura.getEnvelopeStatusResponse ING.EFatura.ClientEInvoiceServicesPort.getEnvelopeStatus(ING.EFatura.getEnvelopeStatusRequest1 request)
        {
            return base.Channel.getEnvelopeStatus(request);
        }
        
        public ING.EFatura.getEnvelopeStatusResponseType[] getEnvelopeStatus(ING.EFatura.getEnvelopeStatusRequest getEnvelopeStatusRequest)
        {
            ING.EFatura.getEnvelopeStatusRequest1 inValue = new ING.EFatura.getEnvelopeStatusRequest1();
            inValue.getEnvelopeStatusRequest = getEnvelopeStatusRequest;
            ING.EFatura.getEnvelopeStatusResponse retVal = ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getEnvelopeStatus(inValue);
            return retVal.getEnvelopeStatusResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ING.EFatura.getEnvelopeStatusResponse> ING.EFatura.ClientEInvoiceServicesPort.getEnvelopeStatusAsync(ING.EFatura.getEnvelopeStatusRequest1 request)
        {
            return base.Channel.getEnvelopeStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ING.EFatura.getEnvelopeStatusResponse> getEnvelopeStatusAsync(ING.EFatura.getEnvelopeStatusRequest getEnvelopeStatusRequest)
        {
            ING.EFatura.getEnvelopeStatusRequest1 inValue = new ING.EFatura.getEnvelopeStatusRequest1();
            inValue.getEnvelopeStatusRequest = getEnvelopeStatusRequest;
            return ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getEnvelopeStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ING.EFatura.getInvoiceViewResponse1 ING.EFatura.ClientEInvoiceServicesPort.getInvoiceView(ING.EFatura.getInvoiceViewRequest1 request)
        {
            return base.Channel.getInvoiceView(request);
        }
        
        public ING.EFatura.getInvoiceViewResponse getInvoiceView(ING.EFatura.getInvoiceViewRequest getInvoiceViewRequest)
        {
            ING.EFatura.getInvoiceViewRequest1 inValue = new ING.EFatura.getInvoiceViewRequest1();
            inValue.getInvoiceViewRequest = getInvoiceViewRequest;
            ING.EFatura.getInvoiceViewResponse1 retVal = ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getInvoiceView(inValue);
            return retVal.getInvoiceViewResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ING.EFatura.getInvoiceViewResponse1> ING.EFatura.ClientEInvoiceServicesPort.getInvoiceViewAsync(ING.EFatura.getInvoiceViewRequest1 request)
        {
            return base.Channel.getInvoiceViewAsync(request);
        }
        
        public System.Threading.Tasks.Task<ING.EFatura.getInvoiceViewResponse1> getInvoiceViewAsync(ING.EFatura.getInvoiceViewRequest getInvoiceViewRequest)
        {
            ING.EFatura.getInvoiceViewRequest1 inValue = new ING.EFatura.getInvoiceViewRequest1();
            inValue.getInvoiceViewRequest = getInvoiceViewRequest;
            return ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getInvoiceViewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ING.EFatura.getRAWUserListResponse1 ING.EFatura.ClientEInvoiceServicesPort.getRAWUserList(ING.EFatura.getRAWUserListRequest1 request)
        {
            return base.Channel.getRAWUserList(request);
        }
        
        public ING.EFatura.getRAWUserListResponse getRAWUserList(ING.EFatura.getRAWUserListRequest getRAWUserListRequest)
        {
            ING.EFatura.getRAWUserListRequest1 inValue = new ING.EFatura.getRAWUserListRequest1();
            inValue.getRAWUserListRequest = getRAWUserListRequest;
            ING.EFatura.getRAWUserListResponse1 retVal = ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getRAWUserList(inValue);
            return retVal.getRAWUserListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ING.EFatura.getRAWUserListResponse1> ING.EFatura.ClientEInvoiceServicesPort.getRAWUserListAsync(ING.EFatura.getRAWUserListRequest1 request)
        {
            return base.Channel.getRAWUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ING.EFatura.getRAWUserListResponse1> getRAWUserListAsync(ING.EFatura.getRAWUserListRequest getRAWUserListRequest)
        {
            ING.EFatura.getRAWUserListRequest1 inValue = new ING.EFatura.getRAWUserListRequest1();
            inValue.getRAWUserListRequest = getRAWUserListRequest;
            return ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getRAWUserListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ING.EFatura.getInvResponsesResponse1 ING.EFatura.ClientEInvoiceServicesPort.getInvResponses(ING.EFatura.getInvResponsesRequest1 request)
        {
            return base.Channel.getInvResponses(request);
        }
        
        public ING.EFatura.getInvResponsesResponse getInvResponses(ING.EFatura.getInvResponsesRequest getInvResponsesRequest)
        {
            ING.EFatura.getInvResponsesRequest1 inValue = new ING.EFatura.getInvResponsesRequest1();
            inValue.getInvResponsesRequest = getInvResponsesRequest;
            ING.EFatura.getInvResponsesResponse1 retVal = ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getInvResponses(inValue);
            return retVal.getInvResponsesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ING.EFatura.getInvResponsesResponse1> ING.EFatura.ClientEInvoiceServicesPort.getInvResponsesAsync(ING.EFatura.getInvResponsesRequest1 request)
        {
            return base.Channel.getInvResponsesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ING.EFatura.getInvResponsesResponse1> getInvResponsesAsync(ING.EFatura.getInvResponsesRequest getInvResponsesRequest)
        {
            ING.EFatura.getInvResponsesRequest1 inValue = new ING.EFatura.getInvResponsesRequest1();
            inValue.getInvResponsesRequest = getInvResponsesRequest;
            return ((ING.EFatura.ClientEInvoiceServicesPort)(this)).getInvResponsesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientEInvoiceServicesPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientEInvoiceServicesPort))
            {
                return new System.ServiceModel.EndpointAddress("http://fitcons.com/eInvoice/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ClientEInvoiceServicesPortClient.GetBindingForEndpoint(EndpointConfiguration.ClientEInvoiceServicesPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ClientEInvoiceServicesPortClient.GetEndpointAddress(EndpointConfiguration.ClientEInvoiceServicesPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ClientEInvoiceServicesPort,
        }
    }
}
